# only runs macos until github actions switches over

trigger:
- master

variables:
  testKind: 'default'

strategy:
  matrix:
    mac-stable:
      imageName: 'macos-10.13'
      rustup_toolchain: stable

pool:
  vmImage: $(imageName)

steps:
  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUSTUP_TOOLCHAIN
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    displayName: Install rust
    condition: ne( variables['Agent.OS'], 'Windows_NT' )
  - script: |
      curl -sSf -o rustup-init.exe https://win.rustup.rs
      rustup-init.exe -y --default-toolchain %RUSTUP_TOOLCHAIN%
      echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin"
    displayName: Windows install rust
    condition: eq( variables['Agent.OS'], 'Windows_NT' )
  - script: cargo build --all --release
    displayName: Cargo build
    condition: eq( variables['testKind'], 'default' )
  - script: cargo test --all --release
    displayName: Cargo test
    condition: eq( variables['testKind'], 'default' )
